In [33]:
from google.colab import files
import numpy as np
import pandas as pd
import io
import re
from string import punctuation
from sklearn.feature_extraction.text import CountVectorizer
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
import warnings
warnings.filterwarnings("ignore")

In [5]:
uploaded = files.upload()


Saving amazon.csv to amazon.csv


In [20]:
df = pd.read_csv(io.BytesIO(uploaded['amazon.csv']))
df

product_id                                       product_name  \
0     B07JW9H4J1  Wayona Nylon Braided USB to Lightning Fast Cha...   
1     B098NS6PVG  Ambrane Unbreakable 60W / 3A Fast Charging 1.5...   
2     B096MSW6CT  Sounce Fast Phone Charging Cable & Data Sync U...   
3     B08HDJ86NZ  boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...   
4     B08CF3B7N1  Portronics Konnect L 1.2M Fast Charging 3A 8 P...   
...          ...                                                ...   
1460  B08L7J3T31  Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...   
1461  B01M6453MB  Prestige Delight PRWO Electric Rice Cooker (1 ...   
1462  B009P2LIL4  Bajaj Majesty RX10 2000 Watts Heat Convector R...   
1463  B00J5DYCCA  Havells Ventil Air DSP 230mm Exhaust Fan (Pist...   
1464  B01486F4G6  Borosil Jumbo 1000-Watt Grill Sandwich Maker (...   

                                               category discounted_price  \
0     Computers&Accessories|Accessories&Peripherals|...             ₹399   
1     Computers&Accessories|Accessories&Peripherals|...             ₹199   
2     Computers&Accessories|Accessories&Peripherals|...             ₹199   
3     Computers&Accessories|Accessories&Peripherals|...             ₹329   
4     Computers&Accessories|Accessories&Peripherals|...             ₹154   
...                                                 ...              ...   
1460  Home&Kitchen|Kitchen&HomeAppliances|WaterPurif...             ₹379   
1461  Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...           ₹2,280   
1462  Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...           ₹2,219   
1463  Home&Kitchen|Heating,Cooling&AirQuality|Fans|E...           ₹1,399   
1464  Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...           ₹2,863   

     actual_price discount_percentage rating rating_count  \
0          ₹1,099                 64%    4.2       24,269   
1            ₹349                 43%    4.0       43,994   
2          ₹1,899                 90%    3.9        7,928   
3            ₹699                 53%    4.2       94,363   
4            ₹399                 61%    4.2       16,905   
...           ...                 ...    ...          ...   
1460         ₹919                 59%      4        1,090   
1461       ₹3,045                 25%    4.1        4,118   
1462       ₹3,080                 28%    3.6          468   
1463       ₹1,890                 26%      4        8,031   
1464       ₹3,690                 22%    4.3        6,987   

                                          about_product  \
0     High Compatibility : Compatible With iPhone 12...   
1     Compatible with all Type C enabled devices, be...   
2     【 Fast Charger& Data Sync】-With built-in safet...   
3     The boAt Deuce USB 300 2 in 1 cable is compati...   
4     [CHARGE & SYNC FUNCTION]- This cable comes wit...   
...                                                 ...   
1460  SUPREME QUALITY 90 GRAM 3 LAYER THIK PP SPUN F...   
1461                       230 Volts, 400 watts, 1 Year   
1462  International design and styling|Two heat sett...   
1463  Fan sweep area: 230 MM ; Noise level: (40 - 45...   
1464  Brand-Borosil, Specification – 23V ~ 5Hz;1 W...   

                                                user_id  \
0     AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...   
1     AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...   
2     AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...   
3     AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...   
4     AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...   
...                                                 ...   
1460  AHITFY6AHALOFOHOZEOC6XBP4FEA,AFRABBODZJZQB6Z4U...   
1461  AFG5FM3NEMOL6BNFRV2NK5FNJCHQ,AGEINTRN6Z563RMLH...   
1462  AGVPWCMAHYQWJOQKMUJN4DW3KM5Q,AF4Q3E66MY4SR7YQZ...   
1463  AF2JQCLSCY3QJATWUNNHUSVUPNQQ,AFDMLUXC5LS5RXDJS...   
1464  AFGW5PT3R6ZAVQR4Y5MWVAKBZAYA,AG7QNJ2SCS5VS5VYY...   

                                              user_name  \
0     Manav,Adarsh gupta,Sunde

In [18]:
#dfReview for review title and review content
dfReview = df[['review_title','review_content','about_product']]
dfReview

review_title  \
0     Satisfied,Charging is really fast,Value for mo...   
1     A Good Braided Cable for Your Type C Device,Go...   
2     Good speed for earlier versions,Good Product,W...   
3     Good product,Good one,Nice,Really nice product...   
4     As good as original,Decent,Good one for second...   
...                                                 ...   
1460  Received the product without spanner,Excellent...   
1461  ok,everything was good couldn't return bcoz I ...   
1462  very good,Work but front melt after 2 month,Go...   
1463  Fan Speed is slow,Good quality,Good product,go...   
1464  Works perfect,Ok good product,Nice Product. Re...   

                                         review_content  \
0     Looks durable Charging is fine tooNo complains...   
1     I ordered this cable to connect my phone to An...   
2     Not quite durable and sturdy,https://m.media-a...   
3     Good product,long wire,Charges good,Nice,I bou...   
4     Bought this instead of original apple, does th...   
...                                                 ...   
1460  I received product without spanner,Excellent p...   
1461  ok,got everything as mentioned but the measuri...   
1462  plastic but cool body ,u have to find sturdy s...   
1463  I have installed this in my kitchen working fi...   
1464  It does it job perfectly..only issue is temp c...   

                                          about_product  
0     High Compatibility : Compatible With iPhone 12...  
1     Compatible with all Type C enabled devices, be...  
2     【 Fast Charger& Data Sync】-With built-in safet...  
3     The boAt Deuce USB 300 2 in 1 cable is compati...  
4     [CHARGE & SYNC FUNCTION]- This cable comes wit...  
...                                                 ...  
1460  SUPREME QUALITY 90 GRAM 3 LAYER THIK PP SPUN F...  
1461                       230 Volts, 400 watts, 1 Year  
1462  International design and styling|Two heat sett...  
1463  Fan sweep area: 230 MM ; Noise level: (40 - 45...  
1464  Brand-Borosil, Specification – 23V ~ 5Hz;1 W...  

[1465 rows x 3 columns]

In [34]:
#replace capital letters and remove punctuation
for column in range(3):
  dfReview.iloc[:,column] = dfReview.iloc[:,column].apply(lambda x: x.lower())
  dfReview.iloc[:,column] = dfReview.iloc[:,column].apply((lambda x: re.sub(r"http\S+"," ",x)))
  dfReview.iloc[:,column] = dfReview.iloc[:,column].apply((lambda x: re.sub('[^a-zA-z0-9\s]'," ",x)))
dfReview

review_title  \
0     satisfied charging is really fast value for mo...   
1     a good braided cable for your type c device go...   
2     good speed for earlier versions good product w...   
3     good product good one nice really nice product...   
4     as good as original decent good one for second...   
...                                                 ...   
1460  received the product without spanner excellent...   
1461  ok everything was good couldn t return bcoz i ...   
1462  very good work but front melt after 2 month go...   
1463  fan speed is slow good quality good product go...   
1464  works perfect ok good product nice product  re...   

                                         review_content  \
0     looks durable charging is fine toono complains...   
1     i ordered this cable to connect my phone to an...   
2     not quite durable and sturdy     m media amazo...   
3     good product long wire charges good nice i bou...   
4     bought this instead of original apple  does th...   
...                                                 ...   
1460  i received product without spanner excellent p...   
1461  ok got everything as mentioned but the measuri...   
1462  plastic but cool body  u have to find sturdy s...   
1463  i have installed this in my kitchen working fi...   
1464  it does it job perfectly  only issue is temp c...   

                                          about_product  
0     high compatibility   compatible with iphone 12...  
1     compatible with all type c enabled devices  be...  
2       fast charger  data sync  with built in safet...  
3     the boat deuce usb 300 2 in 1 cable is compati...  
4     [charge   sync function]  this cable comes wit...  
...                                                 ...  
1460  supreme quality 90 gram 3 layer thik pp spun f...  
1461                       230 volts  400 watts  1 year  
1462  international design and styling two heat sett...  
1463  fan sweep area  230 mm   noise level   40   45...  
1464  brand borosil  specification     23v   5hz 1 w...  

[1465 rows x 3 columns]

In [32]:
#tokenize, build vocab, and add paddings on review_title
tokenizer = Tokenizer(split=' ')
tokenizer.fit_on_texts(dfReview['review_title'].values)
review_title = tokenizer.texts_to_sequences(dfReview['review_title'].values)
review_title = pad_sequences(review_title)

#tokenize, build vocab, and add paddings on review_content
tokenizer = Tokenizer(num_words=2000, split=' ')
tokenizer.fit_on_texts(dfReview['review_content'].values)
review_content = tokenizer.texts_to_sequences(dfReview['review_content'].values)
review_content = pad_sequences(review_content)

#tokenize, build vocab, and add paddings on 
tokenizer = Tokenizer(num_words=2000, split=' ')
tokenizer.fit_on_texts(dfReview['about_product'].values)
about_product = tokenizer.texts_to_sequences(dfReview['about_product'].values)
about_product = pad_sequences(about_product)

print(review_title)
print(review_content)
print(about_product)

[[  0   0   0 ... 136 252   1]
 [  0   0   0 ...  25  51 354]
 [  0   0   0 ...  75   6   2]
 ...
 [  0   0   0 ...   2   6   2]
 [  0   0   0 ...   6   2  64]
 [  0   0   0 ...  16   2   1]]
[[   0    0    0 ...  101    7   75]
 [   0    0    0 ...   12   18  508]
 [   0    0    0 ...   93   53   13]
 ...
 [   0    0    0 ...   13   53   13]
 [   0    0    0 ...   97  442  311]
 [   0    0    0 ...   56 1038   28]]
[[   0    0    0 ...    3  251  454]
 [   0    0    0 ...  143    6  108]
 [   0    0    0 ...  152   15   59]
 ...
 [   0    0    0 ... 1079  549    9]
 [   0    0    0 ... 1217 1635 1274]
 [   0    0    0 ...    1   70  464]]
